{
	"version": 1494579266,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/tiledbackground.png",
		"images/ground1-sheet0.png",
		"images/ground2-sheet0.png",
		"images/ground3-sheet0.png",
		"images/tiledbackground2.png",
		"images/tiledbackground3.png",
		"images/sprite2-sheet0.png",
		"images/tree-sheet0.png",
		"images/block-sheet0.png",
		"images/sprite-sheet0.png",
		"images/hero-sheet0.png",
		"images/hero-sheet1.png",
		"images/player-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/bird-sheet0.png",
		"images/granicaptak-sheet0.png",
		"images/coinbox-sheet0.png",
		"images/coin-sheet0.png",
		"images/boar-sheet0.png",
		"images/boar-sheet1.png",
		"images/brawo-sheet0.png",
		"images/bullet-sheet0.png",
		"media/bump1.m4a",
		"media/bump1.ogg",
		"media/cancel - 1.m4a",
		"media/cancel - 1.ogg",
		"media/airshot1.m4a",
		"media/airshot1.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}